# Generated by Django 5.1.2 on 2025-06-14 00:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transacao_externo', models.CharField(max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('id_cliente', models.CharField(max_length=100)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('cidade_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('processada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('score_fraude', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente de Análise'), ('Confirmada', 'Fraude Confirmada'), ('Segura', 'Transação Segura')], default='Pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detector.transacao')),
            ],
        ),
    ]
